namespace Oxx.Backend.Generators.TypedValues.Generator;

internal static class FileCreationHelpers
{
	private const string Authors = "Kenneth Hoff";
	private const string PackageName = "Oxx.Backend.Generators.TypedValues";
	public static readonly string RootNamespace = typeof(FileCreationHelpers).Namespace;

	private static readonly Version AssemblyVersion = typeof(FileCreationHelpers).Assembly.GetName().Version;

	public static readonly string HeaderTemplate =
		$"""
		/* 
		 * This file is auto-generated by {PackageName}
		 * Version: {AssemblyVersion}
		 * Authors: {Authors}
		 */
		""";

}

