namespace Oxx.Backend.Generators.PocoSchema.Core.Configuration.Abstractions;

public enum FileDeletionMode
{
	/// <summary> Will not delete anything, but will overwrite existing files </summary>
	None,
	/// <summary> Will delete all files before generating new ones. Will exit if directory contains files that are not generated by this tool </summary>
	All,
	/// <summary> Will delete all files before generating new ones. </summary>
	ForcedAll,
}